name: Frontend CI

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'client/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v3

      - name: Set up JS environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run tests
        working-directory: client
        run: npm run test